name: allonsyapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: 2.1.0

  flutter_screenutil: ^5.1.1

  rxdart: ^0.27.3

  flutter_barcode_scanner: ^2.0.0

  flutter_stripe: ^3.1.0

  image_picker: ^0.8.4+4

  http: ^0.13.4

  flip_card: ^0.6.0

  firebase_storage: ^10.2.5

  brasil_fields: ^1.4.5

  fluttertoast: ^8.0.8

  auth_buttons: ^1.0.1+4

  firebase_auth: ^3.1.1

  firebase_messaging: ^11.1.0

  permission_handler: ^8.3.0

  passcode_screen: ^2.0.1

  flutter_local_notifications: ^9.1.4

  google_sign_in: ^5.0.7

  firebase_analytics: ^8.2.0

  carousel_slider: ^4.0.0

  lottie: ^1.1.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0

  charts_flutter: ^0.12.0

  flutter_switch: ^0.3.2

  cpf_cnpj_validator: ^2.0.0

  qr_flutter: ^4.0.0

  flutter_circular_text: ^0.3.1

  syncfusion_flutter_datepicker: ^20.1.48

  credit_card_type_detector: ^2.0.0

  cloud_functions: ^3.2.17

  internet_connection_checker: ^0.0.1+4

  overlay_support: ^2.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - hat.png
    - delivery.png
    - lf20_xigjqt0e.json
    - mastercard.png
    - contact_less.png
    - visa.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Salad1
       fonts:
         - asset: icons/Salad1.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
